TXPhotozStack:
    chunk_rows: 100000

PZPDFMLZ:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000
    
TXPhotozPlots:
    plot_src: True
    plot_lens: False

TXTruthLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut
    
TXLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut

TXTwoPoint:
    bin_slop: 0.0
    delta_gamma: 0.02
    do_pos_pos: False
    do_shear_shear: True
    do_shear_pos: False
    flip_g2: False
    shear_catalog_type: 'lensfit'
    # use true when using metacal shears
    verbose: 0
    min_sep: 0.5
    max_sep: 300
    nbins: 9
    every_nth: 10000
    shear_prefix: ''
    var_method: 'shot'
    reduce_randoms_size: 0.99
    subtract_mean_shear: False
    do_weighted_npairs: True

TXSourceSelector:
    bands: ri #used for selection
    T_cut: 0.0
    s2n_cut: 0.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.1, 0.3, 0.5, 0.7, 0.9, 1.2]
    nsrc: 5
    nlens: 0
    shear_catalog_type: 'lensfit'
    input_pz: True
    shear_prefix: ''
    input_m_is_weighted: False
    # may also need one for r_cpar_cut

TXDiagnosticMaps:
    chunk_rows: 100000  # Number of rows to process at once
    sparse: True  # Generate sparse maps - faster if using small areas
    snr_threshold: 10.0
    snr_delta: 1.0
    pixelization: healpix
    nside: 2048
    # pixelization: gnomonic
    # # 
    pixel_size: 0.2
    ra_cent: 62.
    dec_cent: -35.
    npix_x: 60
    npix_y: 60

TXJackknifeCenters:
    every_nth: 100


TXTwoPointFourier:
    chunk_rows: 100000
    flip_g2: False

TXDiagnosticPlots:
    psf_prefix: "psf_"
    shear_prefix: ""

TXSourceMaps:
    sparse: True  # Generate sparse maps - faster if using small areas
    nside: 2048

TXLensMaps:
    sparse: True  # Generate sparse maps - faster if using small areas

# For redmagic mapping
TXExternalLensMaps:
    chunk_rows: 100000
    sparse: True
    pixelization: healpix
    nside: 2048


TXBlinding: 
    seed: 3212
    #Omega_b: [0.0485, 3.0] ## fiducial_model_value, shift_sigma
    #Omega_c: [0.2, 1.0]
    #h: [0.682, 3.0]
    #sigma8: [0.80, 1.0]
    #n_s: [0.971, 3.0]

TXMainMaps:
    nside: 2048

TXAuxiliaryMaps:
    nside: 2048
   # flag_exponent_max: 8
    #dilate: True
    psf_prefix: psf_
    bright_obj_threshold: 22.0 # The magnitude threshold for a object to be counted as bright
    depth_band : i
    snr_threshold: 10.0  # The S/N value to generate maps for (e.g. 5 for 5-sigma depth)
    snr_delta: 1.0  # The range threshold +/- delta is used for finding objects at the boundary
    sparse: False

TXRealGaussianCovariance:
    min_sep: 0.5
    max_sep: 300.
    nbins: 9
    pickled_wigner_transform: data/example/inputs/wigner.pkl
    use_true_shear: False

TXSimpleMask:
    depth_cut : 10.0
    bright_object_max: 10.0

TXGammaTBrightStars: {}

TXGammaTDimStars: {}

TXGammaTRandoms: {}

TXGammaTFieldCenters: {}