TXPhotozPlots:
    plot_src: True
    plot_lens: False

TXSourceSelector:
    bands: ri #used for selection
    T_cut: 0.0
    s2n_cut: 0.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.3, 0.6, 0.9, 1.2, 1.5]
    chunk_rows: 100000
    nsrc: 4
    nlens: 0
    # lens selection
    select_lens: False
    shear_catalog_type: 'lensfit'
    shear_prefix: ''
    input_pz: True
    true_z: False
    # may also need one for r_cpar_cut

TXLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.0,0.2,0.4]
    cperp_cut: 0.2
    r_cpar_cut: 13.5
    r_lo_cut: 16.0
    r_hi_cut: 21.6
    i_lo_cut: 17.5
    i_hi_cut: 21.9
    r_i_cut: 2.0
    # may also need one for r_cpar_cut

TXTwoPoint:
    binslop: 0.01
    do_pos_pos: False
    min_sep: 0.316
    max_sep: 316
    nbins: 31
    do_shear_shear: True
    do_shear_pos: False
    flip_g2: False
    shear_catalog_type: 'lensfit'
    # use true when using metacal shears
    verbose: 0
    var_methods: 'jackknife'

TXDiagnosticPlots:
    psf_prefix: psf_
    shear_prefix: ''
    shear_catalog_type: 'lensfit'

TXSourceMaps:
    pixelization: healpix
    sparse: False  # Generate sparse maps - faster if using small areas
    nside: 4096
    shear_catalog_type: 'lensfit'
    true_shear: False

TXLensMaps:
    pixelization: healpix
    sparse: False  # Generate sparse maps - faster if using small areas
    nside: 4096

TXMainMaps:
    pixelization: healpix
    nside: 4096
    sparse: False
    shear_catalog_type: 'lensfit'

TXAuxiliaryMaps:
    nside: 4096
    sparse: False
    dilate: False
    psf_prefix: mcal_psf_
    bright_obj_threshold: 16 # The magnitude threshold for a object to be counted as bright
    depth_band : i
    snr_threshold: 5.0  # The S/N value to generate maps for (e.g. 5 for 5-sigma depth)
    snr_delta: 1.0  # The range threshold +/- delta is used for finding objects at the boundary
    shear_catalog_type: 'lensfit'
    
TXMapPlots:
    projection: "moll"

TXJackknifeCenters:
    npatch: 5

TXRealGaussianCovariance:
    min_sep: 0.316
    max_sep: 316
    nbins: 31

TXDensityMaps:
    pixelization: healpix
    nside: 4096
    sparse: False
    shear_catalog_type: 'lensfit'

TXLensMaps:
    nside: 4096

TXGammaTBrightStars: {}

TXGammaTDimStars: {}

TXGammaTRandoms: {}

TXGammaTFieldCenters: {}

TXSimpleMask:
    depth_cut: 0
    bright_object_max: 100
    shear_catalog_type: 'lensfit'


