
PZPDFMLZ:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000

TXPhotozStack:
    chunk_rows: 100000
    
TXPhotozPlots:
    plot_src: True
    plot_lens: False

TXSourceSelector:
    bands: ri #used for selection
    T_cut: 0.0
    s2n_cut: 10.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.15, 0.5, 0.75, 1.0, 1.5]
    chunk_rows: 100000
    nsrc: 4
    nlens: 0
    # lens selection
    select_lens: False
    apply_flag_cut: True
    shear_catalog_type: 'lensfit'
    shear_prefix: ''
    input_pz: True
    # may also need one for r_cpar_cut

TXTruthLensSelector:
    # Mag cuts
    chunk_rows: 100000
    lens_zbin_edges: [0.15,0.5,0.75,1.0,1.5]
    cperp_cut: 100
    r_cpar_cut: 100
    r_lo_cut: 0
    r_hi_cut: 30
    i_lo_cut: 0
    i_hi_cut: 24.5
    r_i_cut: 100
    # may also need one for r_cpar_cut

TXSimpleMask:
    depth_cut: 24.5

TXMainMaps:
    nside: 1024

TXTwoPoint:
    binslop: 0.1
    delta_gamma: 0.02
    do_pos_pos: True
    min_sep: 0.316
    max_sep: 316
    nbins: 31
    do_shear_shear: True
    do_shear_pos: True
    flip_g2: False
    m_from_cat: True
    c_from_cat: True
    shear_catalog_type: 'lensfit'
    # use true when using metacal shears
    verbose: 0
TXTrueNumberDensity:
    zmax: 3
    nz: 301
    
TXAuxiliaryMaps:
    snr_threshold: 10

TXDiagnosticPlots:
    shear_prefix: ''
    psf_prefix: 'psf_'    
TXDiagnosticMaps:
    chunk_rows: 100000  # Number of rows to process at once
    sparse: True  # Generate sparse maps - faster if using small areas
    snr_threshold: 10.0
    snr_delta: 1.0
    pixelization: healpix
    nside: 1024
    compute_lens: False
    # pixelization: gnomonic
    # # 
    pixel_size: 0.2
    ra_cent: 62.
    dec_cent: -35.
    npix_x: 60
    npix_y: 60
    shear_type: 'lensfit'

TXNoiseMaps:
    shear_prefix: ''

TXTwoPointFourier:
    chunk_rows: 100000
    flip_g2: False
