TXSourceSelector:
    bands: riz
    # only using the recommended metacal flag cut 
    T_cut: 0.0
    s2n_cut: 0.0
    max_rows: 1000
    delta_gamma: 0.02
    source_zbin_edges: [0.2, 0.43, 0.63, 0.9, 1.3]
    input_pz: True
   # lens selection
    shear_catalog_type: 'metacal'
    shear_prefix: 'mcal_'
    true_z: False

TXSourceMaps:
    pixelization: healpix
    sparse: False
    nside: 4096

TXTwoPoint:
    bin_slop: 0.01
    delta_gamma: 0.02
    do_pos_pos: False
    do_shear_shear: True
    do_shear_pos: False
    flip_g2: False
    shear_catalog_type: 'metacal'
    # use true when using metacal shears
    verbose: 0
    var_methods: 'jackknife'

TXDiagnosticPlots:
    psf_prefix: mcal_psf_
    shear_prefix: mcal_

TXSourceMaps:
    pixelization: healpix
    sparse: False  # Generate sparse maps - faster if using small areas
    nside: 4096

TXLensMaps:
    pixelization: healpix
    sparse: False  # Generate sparse maps - faster if using small areas
    nside: 4096

# For redmagic mapping
TXExternalLensMaps:
    chunk_rows: 100_000
    sparse: False
    pixelization: healpix
    nside: 4096


TXMainMaps:
    pixelization: healpix
    nside: 4096
    sparse: False
    
TXIngestRedmagic:
    lens_zbin_edges: [0.15,0.3,0.45,0.6,0.75,0.9]

TXAuxiliaryMaps:
    nside: 4096
    sparse: False
    dilate: False
    psf_prefix: mcal_psf_
    bright_obj_threshold: 16 # The magnitude threshold for a object to be counted as bright
    depth_band : i
    snr_threshold: 5.0  # The S/N value to generate maps for (e.g. 5 for 5-sigma depth)
    snr_delta: 1.0  # The range threshold +/- delta is used for finding objects at the boundary
    
TXMapPlots:
    projection: "moll"

TXJackknifeCenters:
    npatch: 5

TXRealGaussianCovariance:
    min_sep: 2.5
    max_sep: 250.
    nbins: 20

TXDensityMaps:
    pixelization: healpix
    nside: 4096
    sparse: False

TXGammaTBrightStars: {}

TXGammaTDimStars: {}

TXGammaTRandoms: {}

TXGammaTFieldCenters: {}

TXSimpleMask:
    depth_cut: 0
    bright_object_max: 100