# DESY1 Config File 
# Inputs: Shear, Photometry, Redmagic Lens catalog, Shear Catalog Stacked Photo-z (from calibration) and Star Catalog
# TODOs: Add DES exposure files for null tests


# Values in this section are accessible to all the different stages.
# They can be overridden by individual stages though.
global:
    # This is read by many stages that read complete
    # catalog data, and tells them how many rows to read
    # at once
    chunk_rows: 100000
    # These mapping options are also read by a range of stages
    pixelization: healpix
    nside: 4096
    sparse: False  # Generate sparse maps - faster if using small areas
launcher:
    name: mini
    interval: 1.0

# Where to run the pipeline: cori-interactive, cori-batch, or local
site:
    name: local
    max_threads: 2


modules: txpipe

# Stages to run
stages:
    - name: TXSourceSelector
    - name: TXIngestRedmagic
    - name: TXTracerMetadata     # collate metadata
    - name: TXSourceMaps
    - name: TXExternalLensMaps
    - name: TXAuxiliaryMaps
    - name: TXSimpleMask
    - name: TXDensityMaps
    - name: TXMapPlots
    - name: TXRandomCat          # generate lens bin random catalogs
    - name: TXJackknifeCenters   # Split the area into jackknife regions
    - name: TXTwoPoint           # Compute real-space 2-point correlations
    - name: TXBlinding           # Blind the data following Muir et al
    - name: TXTwoPointPlots      # Make plots of 2pt correlations
    - name: TXRealGaussianCovariance   # Compute covariance of real-space correlations
    #Not doing fourier space calculations for now 
#    - name: TXTwoPointFourier          # Compute power spectra C_ell
#    - name: TXFourierGaussianCovariance # Compute the C_ell covariance
# these last two also require namaster

# Where to put outputs
output_dir: data/desy1/outputs


# configuration settings
config: /global/u1/e/elp25/txpipe-reanalysis/desy1/configs/config.yml

inputs:
    shear_catalog: /global/cscratch1/sd/elp25/TXPipe/data/desy1/inputs/shear_catalog_desy1_masked.h5
    photometry_catalog: /global/cscratch1/sd/elp25/TXPipe/data/desy1/inputs/photometry_catalog_desy1_masked.h5
    exposures: data/desy1/inputs/exposures.hdf5
    star_catalog: /global/projecta/projectdirs/lsst/groups/WL/projects/wl-txpipe-hack/DESY1/DES_psf_catalog.hdf5
    #txpipe expects this calibration table but it is not currently used for this reanalysis
    calibration_table:  /global/projecta/projectdirs/lsst/groups/WL/users/zuntz/data/cosmoDC2-1.1.4_oneyear_unit_response/sample_cosmodc2_w10year_errors.dat
    fiducial_cosmology: /global/u1/e/elp25/txpipe-reanalysis/desy1/data/fiducial_cosmology.yml
    redmagic_catalog: /global/u1/e/elp25/txpipe-reanalysis/desy1/python/newredmagic.fits
    shear_photoz_stack: /global/cscratch1/sd/elp25/txpipe-reanalysis/desy1/data/shear_photoz_stack.hdf5

# if supported by the launcher, restart the pipeline where it left off
# if interrupted
resume: True
# where to put output logs for individual stages
log_dir: data/desy1/logs
# where to put an overall parsl pipeline log
pipeline_log: data/desy1/log.txt