
PZPDFMLZ:
    nz: 301
    zmax: 3.0
    chunk_rows: 100000

TXPhotozStack:
    chunk_rows: 100000
    
TXPhotozPlots:
    plot_src: True
    plot_lens: False

TXSelector:
    bands: ri #used for selection
    T_cut: 0.0
    s2n_cut: 0.0
    max_rows: 1000
    delta_gamma: 0.02
    zbin_edges: [0.1, 0.3, 0.5, 0.7, 0.9]
    chunk_rows: 100000
    nsrc: 4
    nlens: 0
    # lens selection
    select_lens: False
    apply_flag_cut: False
    shear_catalog_type: 'lensfit'
    input_pz: True
    # may also need one for r_cpar_cut

TXTwoPoint:
    binslop: 0
    delta_gamma: 0.02
    do_pos_pos: False
    do_shear_shear: True
    do_shear_pos: False
    flip_g2: False
    shear_catalog_type: 'lensfit'
    # use true when using metacal shears
    verbose: 0

TXDiagnosticMaps:
    chunk_rows: 100000  # Number of rows to process at once
    sparse: True  # Generate sparse maps - faster if using small areas
    snr_threshold: 10.0
    snr_delta: 1.0
    pixelization: healpix
    nside: 1024
    compute_lens: False
    # pixelization: gnomonic
    # # 
    pixel_size: 0.2
    ra_cent: 62.
    dec_cent: -35.
    npix_x: 60
    npix_y: 60
    shear_type: 'lensfit'


TXTwoPointFourier:
    chunk_rows: 100000
    flip_g2: False
